name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Node_CI:
    runs-on: ubuntu-latest
     # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

          
    env:
      working-directory: ./app
      DBURI: ${{ secrets.DBURI }}
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node packages
      run: npm install
    - name: Running Unit Tests
      run: npm test
